sudo: required

dist: trusty

language: node_js

node_js:
  - stable

branches:
  only:
    - master

before_script:
  - npm install
  - npm install -g angular-cli-ghpages

script:
  - ng build --prod --base-href /

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      angular-cli-ghpages --repo=https://GH_TOKEN@github.com/epiclabs-io/browser-media-support.git --name="New release" --email=jesus@epiclabs.io;
    fi